name: Feature request
description: Suggest an improvement or new device support
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: input
    id: device_model
    attributes:
      label: Device model (if requesting support for new hardware)
